# set mouse 
set -g mouse on

# remove the hardcoded esc time
set -sg escape-time 0


#change Pref from C b to C a
unbind C-b
set -g prefix C-a

#to send ctrl a to inner terminal, we'll press it twice
bind C-a send-prefix

#change window splitting 
unbind %
bind w split-window -h

unbind '"'
bind e split-window -v

#vim ke ybindings 
setw -g mode-keys vi

#better reloading
bind r source-file ~/.tmux.conf \; display-message "tmux.conf locked and loaded."

